INSERT INTO ACCOUNT(ACCOUNT_ID,ISADMIN,EMAIL,USERNAME,PASSWORD) VALUES (1,true,'collinmeaney375@gmail.com','collin','password');
INSERT INTO ACCOUNT(ACCOUNT_ID,ISADMIN,EMAIL,USERNAME,PASSWORD) VALUES (2,true,'shivam.aashir@gmail.com','shivam','password');
INSERT INTO ACCOUNT(ACCOUNT_ID,ISADMIN,EMAIL,USERNAME,PASSWORD) VALUES (3,true,'shivam.aa@gmail.com','shivamaashir','password');

INSERT INTO LIBRARY (LIBRARY_ID,NAME,STATUS,ACCOUNT_ID) VALUES (1, 'Angular',1,1);
INSERT INTO LIBRARY (LIBRARY_ID,NAME,STATUS,ACCOUNT_ID) VALUES (2, 'MicroService',0,1);