

ALTER SEQUENCE SQ_LIBRARY_PK RESTART WITH 1;

INSERT INTO LIBRARY (LIBRARY_ID, ACCOUNTID , NAME , NUMBEROFQUESTION , STATUS ) VALUES (SQ_LIBRARY_PK.NEXTVAL ,1,'AJAX',10, 3);
INSERT INTO LIBRARY (LIBRARY_ID, ACCOUNTID , NAME , NUMBEROFQUESTION , STATUS ) VALUES (SQ_LIBRARY_PK.NEXTVAL,1,'Docker',10, 3);
INSERT INTO LIBRARY (LIBRARY_ID, ACCOUNTID , NAME , NUMBEROFQUESTION , STATUS ) VALUES (SQ_LIBRARY_PK.NEXTVAL,2,'C#',10, 2);
INSERT INTO LIBRARY (LIBRARY_ID, ACCOUNTID , NAME , NUMBEROFQUESTION , STATUS ) VALUES (SQ_LIBRARY_PK.NEXTVAL,1,'C',10, 0);
INSERT INTO LIBRARY (LIBRARY_ID, ACCOUNTID , NAME , NUMBEROFQUESTION , STATUS ) VALUES (SQ_LIBRARY_PK.NEXTVAL,1,'Spring ORM',10, 3);
INSERT INTO LIBRARY (LIBRARY_ID, ACCOUNTID , NAME , NUMBEROFQUESTION , STATUS ) VALUES (SQ_LIBRARY_PK.NEXTVAL,1,'HTML/CSS',10, 1);
INSERT INTO LIBRARY (LIBRARY_ID, ACCOUNTID , NAME , NUMBEROFQUESTION , STATUS ) VALUES (SQ_LIBRARY_PK.NEXTVAL,1,'General',10, 2);
INSERT INTO LIBRARY (LIBRARY_ID, ACCOUNTID , NAME , NUMBEROFQUESTION , STATUS ) VALUES (SQ_LIBRARY_PK.NEXTVAL,1,'Jenkins',10, 0);
INSERT INTO LIBRARY (LIBRARY_ID, ACCOUNTID , NAME , NUMBEROFQUESTION , STATUS ) VALUES (SQ_LIBRARY_PK.NEXTVAL,2,'Angular',10, 1);
INSERT INTO LIBRARY (LIBRARY_ID, ACCOUNTID , NAME , NUMBEROFQUESTION , STATUS ) VALUES (SQ_LIBRARY_PK.NEXTVAL,2,'Java',10, 2);
INSERT INTO LIBRARY (LIBRARY_ID, ACCOUNTID , NAME , NUMBEROFQUESTION , STATUS ) VALUES (SQ_LIBRARY_PK.NEXTVAL,1,'JUnit',10, 0);
INSERT INTO LIBRARY (LIBRARY_ID, ACCOUNTID , NAME , NUMBEROFQUESTION , STATUS ) VALUES (SQ_LIBRARY_PK.NEXTVAL,1,'Hibernate',10, 3);
INSERT INTO LIBRARY (LIBRARY_ID, ACCOUNTID , NAME , NUMBEROFQUESTION , STATUS ) VALUES (SQ_LIBRARY_PK.NEXTVAL,2,'sql',10, 1);
INSERT INTO LIBRARY (LIBRARY_ID, ACCOUNTID , NAME , NUMBEROFQUESTION , STATUS ) VALUES (SQ_LIBRARY_PK.NEXTVAL,2,'pl/sql',10, 2);
INSERT INTO LIBRARY (LIBRARY_ID, ACCOUNTID , NAME , NUMBEROFQUESTION , STATUS ) VALUES (SQ_LIBRARY_PK.NEXTVAL,1,'microservice',10, 0);